blue:
  cannons:
    '1':
      radius: 25
      speed: 10
    '2':
      radius: 25
      speed: 10
    '3':
      radius: 25
      speed: 10
    '4':
      radius: 25
      speed: 10
    '5':
      radius: 25
      speed: 10
  recons:
    '1':
      radius: 20
      speed: 10
    '2':
      radius: 20
      speed: 10
red:
  cannons:
    '1':
      radius: 25
      speed: 10
    '2':
      radius: 25
      speed: 10
    '3':
      radius: 25
      speed: 10
    '4':
      radius: 25
      speed: 10
    '5':
      radius: 25
      speed: 10
  recons:
    '1':
      radius: 20
      speed: 10
    '2':
      radius: 20
      speed: 10
